services:
  - type: web
    name: millennium-smartboard
    env: node
    plan: free
    buildCommand: npm install && npm run build && npm run db:seed
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
